-- 1. CREAR UNA BASE DE DATOS 
CREATE DATABASE universidad;

-- NOTA: En Postgres no existe "USE universidad;". 
-- Debes conectarte a la base de datos 'universidad' desde tu cliente SQL (pgAdmin, DBeaver, etc.) antes de ejecutar lo siguiente.

-- 2. CREAR TABLAS BÁSICAS
CREATE TABLE alumno(
    alumno_id INT,
    nombre VARCHAR(100),
    edad INT
); 

CREATE TABLE alumno_2(
    alumno_id INT,
    nombre VARCHAR(100),
    apellido_paterno VARCHAR(50),
    apellido_materno VARCHAR(50),
    fecha_nacimiento DATE,
    correo VARCHAR(45)
);

-- 3. RESTRICCIONES (PRIMARY KEY)
CREATE TABLE alumno_3(
    alumno_id INT PRIMARY KEY,
    nombre VARCHAR(100),
    correo VARCHAR(40) -- Se eliminó una coma extra aquí
);

CREATE TABLE alumno_4(
    alumno_id INT NOT NULL,
    nombre VARCHAR(100),
    correo VARCHAR(40),
    CONSTRAINT pk_alumno_4 PRIMARY KEY (alumno_id)
);

-- Corregido el nombre "aulumno_4" y agregada la coma que faltaba en los valores
INSERT INTO alumno_4 
VALUES (1, 'Panfilo', 'correo@correo.com');

INSERT INTO alumno_4
VALUES (2, 'Monico', 'correo2@correo.com');


-- 4. PRIMARY KEY CON AUTO-INCREMENTAL (IDENTITY)
CREATE TABLE profesor (
    -- En Postgres se usa GENERATED BY DEFAULT AS IDENTITY para el equivalente a IDENTITY
    profesor_id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    edad INT NULL,
    CONSTRAINT pk_profesor PRIMARY KEY (profesor_id) -- Sintaxis corregida
);

-- Al insertar en tablas con IDENTITY, debemos especificar las columnas si no vamos a incluir el ID
INSERT INTO profesor (nombre, edad)
VALUES ('German', 29),
       ('Mari', 22); -- Se eliminaron comas huérfanas

SELECT * FROM profesor;


-- 5. RESTRICCIÓN UNIQUE
CREATE TABLE materia(
    -- Definimos el ID como IDENTITY directamente
    materia_id INT GENERATED BY DEFAULT AS IDENTITY,
    correo VARCHAR(50) NOT NULL,
    CONSTRAINT pk_materia PRIMARY KEY(materia_id),
    CONSTRAINT uq_materia_correo UNIQUE(correo)
);

-- Corregido el nombre de "materia_2" a "materia" que es como se creó arriba
INSERT INTO materia (correo)
VALUES ('correo@correo.com');

INSERT INTO materia (correo)
VALUES ('correo2@correo.com');